apiVersion: v1
kind: Pod
metadata:
  name: res-pod
spec:
  containers:
  - image: nginx:1.14
    name: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
