apiVersion: v1
kind: Pod
metadata:
  name: health-pod
spec:
  containers:
  - image: nginx:1.14
    name: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
